name: Build SensorWrangler with Bazel
on:
  push:
    branches:
      - github-actions

jobs:
  setup-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
        bazelisk: [1.11.0]
        bazel: [4.2.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build CLI
        run: bazel build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 //src/me/danielschaefer/sensorwrangler:Cli
        shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}

      - name: Build GUI
        run: bazel build --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 //src/me/danielschaefer/sensorwrangler:Gui
        shell: bash
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
